//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterLoginMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingList
    {
        public int RideId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> AdminId { get; set; }
        public Nullable<int> CarId { get; set; }
        public string CARName { get; set; }
        public Nullable<int> Seats { get; set; }
        public string PickUp { get; set; }
        public string Drop { get; set; }
        public Nullable<int> Fare { get; set; }
        public Nullable<System.DateTime> PickUpDate { get; set; }
        public Nullable<System.TimeSpan> PickUPTime { get; set; }
        public string Status { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual User User { get; set; }
    }
}
